export const chartStories = [
  "charts-linechart--basic",
  "charts-linechart--long-labels",
  "charts-linechart--dense-data",
  "charts-linechart--negative-values",
  "charts-linechart--empty-state",
  "charts-linechart--dark-mode",
  "charts-linechart--tiny-width",
  "charts-v2linechart--basic",
  "charts-v2linechart--multi-series",
  "charts-v2linechart--null-gaps",
  "charts-v2linechart--area-fill",
  "charts-v2linechart--dense-labels",
  "charts-v2linechart--dark-mode",
  "charts-barchart--basic",
  "charts-barchart--long-labels",
  "charts-barchart--dense-data",
  "charts-barchart--negative-values",
  "charts-barchart--empty-state",
  "charts-barchart--dark-mode",
  "charts-barchart--tiny-width"
] as const;
